[package]
name = "pwrate"
version = "1.2.0"
authors = ["Alex B <pkunk.ab@gmail.com>"]
edition = "2021"
license = "GPL-3.0-only"
keywords = ["pipewire", "gtk", "gui", "utility"]
categories = ["gui", "multimedia"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glib = { version = "0.15.1" }
gtk = { version = "0.4.1", package = "gtk4" }
once_cell = "1.7.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
